-- ============================================================
-- Jyotish AI — Chandra Ashtama + Tara Balam Schema
-- Run this in Supabase SQL Editor AFTER the main schema.sql
-- ============================================================

-- ============================================================
-- 1. MOON DAILY
--    Stores pre-computed Moon longitude + nakshatra per date/location.
--    Shared lookup used by Tara + Ashtama engines.
-- ============================================================
CREATE TABLE IF NOT EXISTS moon_daily (
    id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    date            DATE NOT NULL,
    location_name   TEXT NOT NULL,
    moon_longitude  DOUBLE PRECISION NOT NULL,   -- sidereal (Lahiri)
    moon_rasi_index INTEGER NOT NULL,            -- 0–11
    moon_nak_index  INTEGER NOT NULL,            -- 0–26
    moon_nak_name   TEXT NOT NULL,
    moon_pada       INTEGER NOT NULL,            -- 1–4
    moon_sign       TEXT NOT NULL,
    calculated_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(date, location_name)
);

CREATE INDEX IF NOT EXISTS moon_daily_date_loc_idx ON moon_daily(date, location_name);

-- ============================================================
-- 2. TARA LOOKUP
--    Static 9-Tara table. Position (1–9) cycles from natal nak.
--    Seeded once; never changes.
-- ============================================================
CREATE TABLE IF NOT EXISTS tara_lookup (
    position    INTEGER PRIMARY KEY,   -- 1–9 (offset from natal nak, mod 9)
    tara_name   TEXT NOT NULL,
    nature      TEXT NOT NULL,         -- 'benefic' | 'malefic' | 'neutral'
    colour      TEXT NOT NULL,         -- 'green' | 'red' | 'yellow'
    meaning     TEXT NOT NULL
);

INSERT INTO tara_lookup (position, tara_name, nature, colour, meaning) VALUES
    (1, 'Janma',      'neutral',  'yellow', 'Birth star — mixed results, health focus'),
    (2, 'Sampat',     'benefic',  'green',  'Wealth star — gains, prosperity'),
    (3, 'Vipat',      'malefic',  'red',    'Danger star — obstacles, accidents'),
    (4, 'Kshema',     'benefic',  'green',  'Comfort star — well-being, stability'),
    (5, 'Pratyari',   'malefic',  'red',    'Enemy star — conflicts, setbacks'),
    (6, 'Sadhana',    'benefic',  'green',  'Achievement star — success, fulfilment'),
    (7, 'Naidhana',   'malefic',  'red',    'Death star — loss, danger, avoid major moves'),
    (8, 'Mitra',      'benefic',  'green',  'Friend star — alliances, support'),
    (9, 'Param Mitra','benefic',  'green',  'Best friend star — excellent outcomes')
ON CONFLICT (position) DO NOTHING;

-- ============================================================
-- 3. ASHTAMA LOOKUP
--    For each natal Moon rasi (0–11), records the ashtama rasi
--    (8th sign = natal + 7, mod 12) and display names.
--    Seeded with all 12 combinations.
-- ============================================================
CREATE TABLE IF NOT EXISTS ashtama_lookup (
    natal_rasi_index   INTEGER PRIMARY KEY,   -- 0–11
    natal_rasi_name    TEXT NOT NULL,
    ashtama_rasi_index INTEGER NOT NULL,      -- (natal + 7) % 12
    ashtama_rasi_name  TEXT NOT NULL
);

INSERT INTO ashtama_lookup (natal_rasi_index, natal_rasi_name, ashtama_rasi_index, ashtama_rasi_name) VALUES
    (0,  'Aries',       7,  'Scorpio'),
    (1,  'Taurus',      8,  'Sagittarius'),
    (2,  'Gemini',      9,  'Capricorn'),
    (3,  'Cancer',      10, 'Aquarius'),
    (4,  'Leo',         11, 'Pisces'),
    (5,  'Virgo',       0,  'Aries'),
    (6,  'Libra',       1,  'Taurus'),
    (7,  'Scorpio',     2,  'Gemini'),
    (8,  'Sagittarius', 3,  'Cancer'),
    (9,  'Capricorn',   4,  'Leo'),
    (10, 'Aquarius',    5,  'Virgo'),
    (11, 'Pisces',      6,  'Libra')
ON CONFLICT (natal_rasi_index) DO NOTHING;

-- ============================================================
-- 4. USER DAILY PANCHANGAM
--    Personalised daily record per user: Tara + Ashtama + Chandrabalam.
--    Generated by the 04:30 AM scheduler job.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_daily_panchangam (
    id                   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id              UUID NOT NULL,          -- no FK until auth is wired up
    date                 DATE NOT NULL,

    -- Tara Balam
    tara_position        INTEGER NOT NULL,        -- 1–9
    tara_name            TEXT NOT NULL,
    tara_nature          TEXT NOT NULL,           -- benefic | malefic | neutral
    tara_colour          TEXT NOT NULL,           -- green | red | yellow
    tara_meaning         TEXT NOT NULL,

    -- Chandra Ashtama
    is_chandra_ashtama   BOOLEAN NOT NULL DEFAULT FALSE,
    ashtama_start        TIMESTAMPTZ,
    ashtama_end          TIMESTAMPTZ,
    next_ashtama_date    DATE,                    -- when not currently active

    -- Chandrabalam
    chandrabalam_good    BOOLEAN NOT NULL DEFAULT TRUE,
    moon_house_from_natal INTEGER NOT NULL,       -- 1–12 (Moon's current house counted from natal Moon rasi)

    -- Context
    natal_moon_nak       TEXT NOT NULL,
    natal_moon_rasi      TEXT NOT NULL,
    today_moon_sign      TEXT NOT NULL,
    today_moon_nak       TEXT NOT NULL,

    calculated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE(user_id, date)
);

CREATE INDEX IF NOT EXISTS udp_user_date_idx ON user_daily_panchangam(user_id, date DESC);

-- ============================================================
-- 5. ASHTAMA ALERTS
--    Push notification log for Chandra Ashtama events.
-- ============================================================
CREATE TABLE IF NOT EXISTS ashtama_alerts (
    id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      UUID NOT NULL,
    alert_date   DATE NOT NULL,
    alert_type   TEXT NOT NULL CHECK (alert_type IN ('start', 'end', 'reminder')),
    message      TEXT NOT NULL,
    sent_at      TIMESTAMPTZ,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, alert_date, alert_type)
);

-- ============================================================
-- 6. USER LOCATIONS
--    Current location override per user (for Panchangam calculation).
--    Defaults to the birth location if not set.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_locations (
    user_id    UUID PRIMARY KEY,
    city       TEXT NOT NULL,
    lat        DOUBLE PRECISION NOT NULL,
    lon        DOUBLE PRECISION NOT NULL,
    timezone   TEXT NOT NULL DEFAULT 'Asia/Kolkata',
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ============================================================
-- RLS — match existing pattern
-- ============================================================
ALTER TABLE moon_daily             ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_daily_panchangam  ENABLE ROW LEVEL SECURITY;
ALTER TABLE ashtama_alerts         ENABLE ROW LEVEL SECURITY;
ALTER TABLE user_locations         ENABLE ROW LEVEL SECURITY;
ALTER TABLE tara_lookup            ENABLE ROW LEVEL SECURITY;
ALTER TABLE ashtama_lookup         ENABLE ROW LEVEL SECURITY;

-- Public read for static lookup tables
CREATE POLICY "tara_lookup_public_read"    ON tara_lookup    FOR SELECT USING (true);
CREATE POLICY "ashtama_lookup_public_read" ON ashtama_lookup FOR SELECT USING (true);

-- moon_daily: service role writes, public reads (shared across users)
CREATE POLICY "moon_daily_public_read"     ON moon_daily FOR SELECT USING (true);
CREATE POLICY "moon_daily_service_write"   ON moon_daily FOR ALL USING (auth.role() = 'service_role');

-- Per-user tables: service role writes (scheduler), users read own rows
CREATE POLICY "udp_service_write"  ON user_daily_panchangam FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "alerts_service_write" ON ashtama_alerts      FOR ALL USING (auth.role() = 'service_role');
CREATE POLICY "locations_service_write" ON user_locations   FOR ALL USING (auth.role() = 'service_role');

-- Also add moon_nakshatra_index + moon_rasi_index columns to natal_charts if not present
ALTER TABLE natal_charts
    ADD COLUMN IF NOT EXISTS moon_nakshatra_index INTEGER,
    ADD COLUMN IF NOT EXISTS moon_rasi_index      INTEGER;
