"""Professional analysis content for MA Exam PDF — all 10 use cases."""

CASES = [
    {
        "num": 1,
        "title": "Job Obtained",
        "gender": "Male",
        "birth": "24 October 1977, 9:00 AM",
        "place": "Dharmapuri",
        "dob": "1977-10-24",
        "tob": "09:00",
        "question": "Analyse the astrological causes for obtaining employment on 25 January 2024, with Dasa–Bhukti–Pratyantar and Gochara corroboration.",
        "event_date": "2024-01-25",
        "event_label": "Job obtained — 25 January 2024",
        "natal_analysis": [
            "The native is born with <b>Scorpio lagna (Anuradha)</b> and <b>Moon in Pisces, 5th house (Uttara Bhadrapada)</b>. The career axis is strongly marked: <b>Saturn occupies the 10th house (Leo)</b>, which is the classical signature of steady karma and long-term employment. Saturn as a natural significator of service, when placed in the house of profession, grants the native the capacity to hold structured employment, particularly in organisations requiring discipline and endurance.",
            "The <b>10th lord Sun is placed in Libra, 12th house</b>, indicating career through institutions, large organisations, hospitals, or foreign-linked employers. This does not deny employment; rather, it shows that the job is obtained through institutional channels rather than purely self-employment. <b>Venus and Rahu together in the 11th house (Virgo)</b> create a powerful yoga for sudden gain through networks, referrals, and unconventional opportunities — precisely the pattern of an unexpected job offer.",
            "Ashtakavarga support is favourable: <b>SAV scores for the 6th house (34) and 10th house (37)</b> are both in the Strong range, confirming that the houses of service and career can deliver tangible results when activated by Dasa and transit.",
        ],
        "aspect_analysis": [
            "Under traditional Parasara drishti (all planets aspect the 7th; Mars also 4th &amp; 8th; Jupiter 5th &amp; 9th; Saturn 3rd &amp; 10th; Rahu/Ketu 3rd &amp; 11th), the employment houses receive decisive planetary gaze. <b>Sun and Mercury from the 12th house cast their 7th aspect on the 6th house</b> — institutional/service employment through the 12th-house channel (hospitals, large organisations, foreign-linked employers). This directly supports job acquisition through an employer rather than self-employment.",
            "<b>Saturn in the 10th aspects the 7th house (by 10th aspect), 4th house (by 3rd aspect), and 12th house (by 3rd aspect)</b> — linking career (10th) to contracts/partnerships (7th) and institutional service (12th). <b>Moon from the 5th aspects the 11th house</b>, connecting merit/intelligence to gains. <b>Mars from the 9th aspects the 12th house (8th drishti)</b>, reinforcing career through institutions. At Gochara on the event date, <b>transit Saturn in the 4th casts its 10th aspect on the natal 10th house</b>, triggering natal Saturn seated in the career bhava.",
        ],
        "dasa_analysis": [
            "On 25 January 2024, the native was running <b>Venus Mahadasha, Moon Antardasha, and Rahu Pratyantar Dasa</b> (Rahu PD approximately 12 January – 13 April 2024). Venus as lord of the 7th and 12th houses, placed natally in the 11th, rules contracts, employers, and gains — making Venus MD the primary permission for taking up employment.",
            "<b>Moon Antardasha</b> activates the 9th lord in the 5th house, linking fortune (9th) with merit and intelligence (5th). This sub-period supports job acquisition through qualification and righteous effort. <b>Rahu Pratyantar</b> within this window is the sudden-offer timer — Rahu natally in the 11th with Venus amplifies network-based, unexpected employment.",
            "Although Venus–Moon is an enemy relationship in Dasa phala, this indicates adjustment in the new role rather than denial of employment. The triple activation of gain houses (11th) through Venus MD, Moon AD (9th lord), and Rahu PD (natal 11th) provides a coherent Dasa explanation for the event date.",
        ],
        "gochara_analysis": [
            "Transit corroboration on 25 January 2024 is equally compelling. <b>Jupiter transiting the 6th house</b> is the primary employment transit in Parasara Gochara — Jupiter in the house of service directly signifies taking up a job. <b>Venus, Mars, and Mercury transiting the 2nd house</b> activate income and salary themes, confirming financial commencement alongside employment.",
            "<b>Saturn in the 4th house</b> aspects the natal 10th house (Leo) by its 7th aspect, triggering the natal Saturn already seated in the career house. <b>Moon transiting the 9th house</b> aligns with the Moon Antardasha, reinforcing the fortune-and-merit dimension of the job offer.",
        ],
        "conclusion": [
            "The obtaining of employment on 25 January 2024 is explained by the integrated operation of three astrological layers. Natal capacity is established through Saturn in the 10th house and strong SAV support for the 6th and 10th houses. Dasa permission is granted by Venus Mahadasha (employer/contract lord in the 11th), Moon Antardasha (9th lord — fortune), and Rahu Pratyantar (sudden network-based offer). Gochara triggers the event through Jupiter in the 6th (service/employment), income planets in the 2nd, and Saturn aspecting the 10th house.",
            "Following the Parasara method — Bhava significators first, then Dasa permission, then Gochara as the final trigger — the chart presents a textbook employment event with no contradictory factors of denial.",
        ],
    },
    {
        "num": 2,
        "title": "Marriage Timing",
        "gender": "Female",
        "birth": "27 June 1997, 1:31 PM",
        "place": "Dharmapuri",
        "dob": "1997-06-27",
        "tob": "13:31",
        "question": "Analyse marriage timing — when marriage is indicated, with Dasa–Bhukti–Pratyantar and Gochara support.",
        "natal_analysis": [
            "The native has <b>Virgo lagna (Chitra)</b> with the <b>7th house in Pisces occupied by Moon and Saturn</b>. This is one of the strongest marriage configurations: the kalatra bhava is directly occupied by the mind (Moon) and the planet of commitment (Saturn). Moon as 11th lord in the 7th creates a yoga of gain through marriage — partnership is central to the native's life fulfilment.",
            "<b>Jupiter, lord of the 7th house, is placed in Capricorn, 5th house (retrograde)</b>. This links the spouse to romance, intelligence, and creative choice rather than purely parental arrangement. Venus as kalatra karaka in Cancer, 11th house, promises fulfilment of marital desire when Venus periods operate. The chart is unequivocally marriage-capable.",
            "Delay factors exist: <b>Saturn in the 7th</b> may postpone marriage until maturity (late 20s). <b>Mars in the lagna</b> creates Manglik dosha, adding intensity and the need for careful horoscope matching. <b>Rahu in the 12th</b> suggests the spouse may come from a different background or through unconventional circumstances. SAV for the 7th house (25) is Good — the house can deliver results when timed.",
        ],
        "aspect_analysis": [
            "Traditional drishti is central to this marriage chart. <b>Mars in the lagna aspects the 7th house by its 4th, 7th, and 8th special aspects</b> — the Manglik configuration directly influences Moon and Saturn seated in Pisces (7th). This adds passion, intensity, and pressure on the marriage axis; matching horoscopes or parihara is advised per tradition.",
            "<b>Saturn occupying the 7th house aspects the 1st house (3rd aspect), 4th house (10th aspect), and 9th house (3rd aspect)</b> — delay in marriage but strong commitment once formed; spouse connected to fortune/dharma (9th). <b>Jupiter in the 5th aspects the 11th house (9th drishti)</b>, linking romance/intelligence to fulfilment of desire (Venus in 11th). <b>Venus in the 11th aspects the 5th house (7th drishti)</b>, creating a mutual 5th–11th drishti exchange supporting love and fulfilment.",
        ],
        "dasa_analysis": [
            "Vimshottari Dasa runs from <b>Saturn at birth (Uttara Bhadrapada nakshatra)</b>. As of 2025–2026, the native is in <b>Ketu Mahadasha with Venus Antardasha (May 2025 – July 2026)</b> — the strongest current marriage window. Venus as kalatra karaka in its own Antardasha directly activates Venus in the 11th house of fulfilment.",
            "Within this Venus AD, the most auspicious Pratyantar periods are: <b>Venus PD (May–July 2025)</b> — peak marriage pulse; <b>Jupiter PD (December 2025 – February 2026)</b> — 7th lord sub-period for legal/spiritual union; <b>Saturn PD (February – April 2026)</b> — Saturn occupies natal 7th, indicating formal commitment and ring ceremony.",
            "Backup windows if the current period passes: <b>Ketu–Moon AD (November 2026 – June 2027)</b> — Moon natally in 7th; <b>Ketu–Jupiter AD (November 2028 – November 2029)</b> — 7th lord sub-period; <b>Venus Mahadasha from December 2031</b> — life's strongest relationship phase if marriage is delayed further.",
        ],
        "gochara_analysis": [
            "<b>Saturn transiting Pisces (natal 7th house)</b> during 2023–2025 forces serious partnership decisions — this is the classic late-20s marriage transit for Virgo lagna. <b>Jupiter transiting Cancer (11th house) in 2026</b> activates the natal Venus house theme, bringing fulfilment and celebration.",
            "<b>Venus transiting the 11th house in mid-2026</b> creates a double-Venus activation ideal for engagement or marriage muhurta. The convergence of Saturn over the 7th (commitment) and Jupiter/Venus over the 11th (fulfilment) in 2026 strongly supports the Ketu–Venus Dasa window.",
        ],
        "conclusion": [
            "Marriage is strongly indicated between <b>late 2025 and mid-2026</b>, with the peak cluster being <b>December 2025 – April 2026</b> (Jupiter and Saturn Pratyantar within Venus Antardasha, with Saturn transiting the 7th house). The nature of marriage combines romance (Jupiter in 5th) with formal commitment (Saturn in 7th); the partner is likely mature and emotionally deep (Moon–Saturn in 7th).",
            "Manglik dosha from Mars in the lagna should be addressed through matching or appropriate remedies per tradition. If marriage does not occur in the primary window, the Ketu–Moon period (late 2026 – mid 2027) serves as the next strong alternative.",
        ],
    },
    {
        "num": 3,
        "title": "Joint Replacement Surgery",
        "gender": "Female",
        "birth": "4 July 1975, 5:00 AM",
        "place": "Dharmapuri",
        "dob": "1975-07-04",
        "tob": "05:00",
        "question": "Analyse the astrological causes for joint replacement surgery on 28 November 2019.",
        "event_date": "2019-11-28",
        "event_label": "Surgery — 28 November 2019",
        "natal_analysis": [
            "The native has <b>Gemini lagna (Mrigashira)</b> with <b>Saturn and Sun in the 1st house</b>. Saturn is the natural karaka for bones, joints, and chronic structural ailments; its placement in the lagna links joint degeneration directly to the physical constitution. As <b>8th lord seated in the 1st house</b>, Saturn also connects the surgery/longevity axis to the body itself.",
            "<b>Rahu in the 6th house (Scorpio, retrograde)</b> amplifies disease patterns — progressive, inflammatory, or difficult-to-diagnose conditions. <b>Ketu with Mercury (12th lord) in the 12th house (Taurus)</b> is the classic hospital-and-surgery signature: Ketu signifies cutting, separation, and replacement of body tissue; the 12th house is confinement and hospitalisation.",
            "<b>Mars as 6th lord in Aries, 11th house with Moon</b> ties the disease lord to long-standing affliction and expenditure. SAV analysis shows <b>H8 = 36 (Strong)</b> supporting surgical intervention survival, while <b>H12 = 19 (Weak)</b> indicates stressful hospital recovery — consistent with major joint replacement.",
        ],
        "aspect_analysis": [
            "<b>Rahu in the 6th house aspects the 8th house (3rd drishti), 12th house (7th drishti), and 4th house (11th drishti)</b> — the nodal axis connects disease (6th) to surgery (8th) and hospitalisation (12th) through traditional drishti. This is a primary surgical signature independent of house occupancy alone.",
            "<b>Mars from the 11th aspects the 6th house (8th drishti)</b> — the 8th lord's gaze on its moolatrikona-linked disease house activates operative intervention on joints. <b>Jupiter from the 10th aspects the 6th house (9th drishti)</b>, bringing medical treatment through professional channels. <b>Ketu in the 12th aspects the 6th house (7th drishti)</b>, completing the Rahu–Ketu nodal drishti on the disease–hospital axis. On the surgery date, <b>transit Saturn in the 7th aspects natal Saturn in the 1st by its 3rd aspect</b>, triggering the joint/bone significator.",
        ],
        "dasa_analysis": [
            "On 28 November 2019, the native was running <b>Rahu Mahadasha, Rahu Antardasha, and Ketu Pratyantar Dasa (17 November 2019 – 14 January 2020)</b>. The surgery date falls precisely within Ketu PD, which began only 11 days before the operation.",
            "<b>Rahu–Rahu (Same lord)</b> at MD–AD level represents peak intensity of natal Rahu in the 6th house — the disease bhava. The nodal pair Rahu (disease/amplification) and Ketu (cutting/replacement) operating together in Dasa is the classical combination for operative procedures involving removal and prosthetic replacement.",
            "At age 44, the event aligns with Saturn-in-lagna chronic joint wear reaching a surgical threshold. The precision of Ketu Pratyantar on the exact operation date is among the strongest Dasa corroborations in this case series.",
        ],
        "gochara_analysis": [
            "On the surgery date, <b>Sun and Moon together transit the 6th house (Scorpio)</b> — double activation of the disease house on the operative day. <b>Transit Rahu over Gemini (natal lagna)</b> directly hits natal Saturn and Sun in the 1st house, placing the body and joint significator under severe nodal stress.",
            "<b>Transit Ketu in the 7th house</b> during Ketu Pratyantar creates a double-Ketu effect — cutting, separation, and replacement of the diseased part. <b>Saturn, Jupiter, and Venus in the 7th</b> add maraka/surgical stress. Transit Saturn's aspect on natal Saturn in the 1st invokes a Saturn-return theme on bones and joints.",
        ],
        "conclusion": [
            "Joint replacement surgery on 28 November 2019 is explained by: (1) natal predisposition through Saturn in the lagna (chronic joint degeneration), Rahu in the 6th (disease), and Ketu in the 12th (hospital/surgical loss of tissue); (2) <b>Rahu MD / Rahu AD / Ketu PD</b> on the exact date — Ketu as the karaka of cutting and prosthetic replacement; (3) Gochara with Sun and Moon in the 6th house and Rahu transiting over natal Saturn in the lagna.",
            "Strong 8th-house SAV supports surviving the procedure; weak 12th-house SAV suggests a longer hospital and recovery phase, which is typical for major joint replacement surgery.",
        ],
    },
    {
        "num": 4,
        "title": "Education & Career",
        "gender": "Male",
        "birth": "21 February 2001, 5:45 AM",
        "place": "Dharmapuri",
        "dob": "2001-02-21",
        "tob": "05:45",
        "question": "Analyse education (school through higher studies) and career direction with Dasa support.",
        "natal_analysis": [
            "The native has <b>Capricorn lagna (Shravana)</b> with <b>Moon and Mercury (retrograde) in the 1st house</b>. Mercury as 9th lord in the lagna is an excellent higher-education yoga — the fortune house lord in the self-house grants intelligence, academic aptitude, and capacity for professional qualification.",
            "<b>Jupiter and Saturn together in the 5th house (Taurus)</b> form a powerful education yoga. Jupiter is the primary Guru/knowledge karaka; Saturn adds discipline and structured academic success. This combination strongly supports degrees, competitive examinations, and professional courses. <b>Venus as 5th lord in Pisces, 3rd house</b> adds communication, writing, arts, and media streams to the educational profile.",
            "For career, <b>the 10th lord Venus is placed in the 3rd house (Pisces)</b>, directing profession toward communication, media, marketing, sales, writing, design, and IT-enabled services. <b>Mars in Scorpio, 11th house (own sign)</b> adds gains through research, finance, and competitive specialist fields. <b>Rahu in the 6th house</b> indicates service-sector, MNC, or foreign-linked employment. SAV H9 (30, Strong) and H10 (29, Good) support both education and career delivery.",
        ],
        "aspect_analysis": [
            "<b>Jupiter in the 5th house aspects the 9th house (9th drishti) and 11th house (5th drishti)</b> — the Guru's special aspects directly link intellect (5th) to higher education (9th) and gains (11th). <b>Venus in the 3rd aspects the 9th house (7th drishti)</b>, connecting communication/courage to fortune and degree completion.",
            "<b>Mars in the 11th aspects the 5th house (8th drishti)</b>, energising competitive academic performance. <b>Saturn in the 5th aspects the 2nd house (3rd drishti), 7th house (7th drishti), and 11th house (10th drishti)</b> — disciplined study leading to income and professional gains. For career, <b>Ketu in the 12th aspects the 10th house (7th drishti)</b>, indicating specialisation or unconventional professional path.",
        ],
        "dasa_analysis": [
            "Education peaks align with Dasa periods: <b>Mars–Mercury AD (2012–2013, age 11–12)</b> — key academic performance with Mercury as 9th lord; <b>Rahu–Jupiter AD (2018–2020, age 17–19)</b> — higher secondary and undergraduate peak; <b>Rahu–Mercury AD (2023–2026, age 22–25)</b> — current phase for postgraduate, certification, and job-oriented skills.",
            "For career establishment, <b>Rahu–Venus Antardasha (April 2027 – April 2030, age 26–29)</b> is the primary window — Venus is the 10th lord, and this sub-period brings stable employment and income in the Venus-ruled communication/media field. <b>Jupiter Mahadasha from October 2033</b> marks major career expansion into teaching, advisory, or senior expert roles.",
            "Currently (2026), the native is in <b>Rahu MD / Ketu AD (April 2026 – April 2027)</b> — a transition phase after skill-building in Rahu–Mercury. This is a preparatory period before the decisive Rahu–Venus career launch.",
        ],
        "conclusion": [
            "The native possesses strong educational potential through Jupiter–Saturn in the 5th house and Mercury (9th lord) in the lagna. Academic peaks occurred during Mars–Mercury (2012–13), Rahu–Jupiter (2018–20), and the ongoing Rahu–Mercury phase (2023–26). Best educational streams: commerce, communication, media, IT, or creative-technical blends.",
            "Career direction is Venus-ruled: communication, media, marketing, writing, design, or IT services, with Mars in the 11th adding finance/research specialist potential. <b>Career establishment is predicted for April 2027 – April 2030 (Rahu–Venus AD)</b>, with major rise during Jupiter Mahadasha from 2033. The current Ketu AD (2026–27) is a transition — complete skills now, and Venus AD will bring stable employment.",
        ],
    },
    {
        "num": 5,
        "title": "House Purchase Timing",
        "gender": "Male",
        "birth": "27 February 1978, 6:55 PM",
        "place": "Coimbatore",
        "dob": "1978-02-27",
        "tob": "18:55",
        "question": "When would this native have bought a house? Analyse property yoga, Dasa windows, and Gochara.",
        "natal_analysis": [
            "The native has <b>Leo lagna (Purva Phalguni)</b> — a fixed sign indicating strong desire for immovable assets and own home. The property yoga is clear and unambiguous: <b>the 4th lord Mars (retrograde) is placed in the 11th house (Gemini) with Jupiter</b>. When the lord of the 4th (home) occupies the 11th (gains), property is acquired through income and savings.",
            "<b>Mars as property karaka with Jupiter (expansion) in the 11th</b> is one of the strongest real-estate fulfilment combinations. <b>Saturn (retrograde) in the lagna</b> indicates land and construction through patience and self-effort. <b>Rahu in the 2nd house</b> suggests bank loan or financial leverage in the purchase. <b>Venus, Sun, and Mercury in the 7th house</b> indicate spouse involvement or legal deed dimensions.",
            "SAV scores for the 4th house (32) and 11th house (33) are both Strong, confirming that property and gains houses are well supported and will deliver results when Dasa activates the 4th lord.",
        ],
        "aspect_analysis": [
            "<b>Rahu in the 2nd house aspects the 4th house (3rd drishti), 8th house (7th drishti), and 12th house (11th drishti)</b> — finance/loan (2nd) drishti on the home bhava (4th) is a classic property-purchase-through-borrowing signature. Rahu's 7th aspect on the 8th adds shared resources and joint finance in the transaction.",
            "<b>Jupiter in the 11th aspects the 3rd house (5th drishti), 5th house (9th drishti), and 7th house (7th drishti)</b> — expansion of gains (11th) through legal/partnership channels (7th) for property. <b>Saturn in the lagna aspects the 3rd, 7th, and 10th houses</b>, indicating self-effort, patience, and long-term construction/land development. <b>Sun, Venus, and Mercury in the 7th aspect the lagna (7th drishti)</b>, showing spouse or legal partner involvement in the purchase deed.",
        ],
        "dasa_analysis": [
            "The <b>primary purchase window is Jupiter Mahadasha / Mars Antardasha (May 2005 – April 2006, age 27–28)</b>. Mars is both the 4th lord and the property karaka — its Antardasha within expansive Jupiter MD directly triggers the Mars+Jupiter in 11th yoga. Peak Pratyantar periods within this AD include <b>Saturn PD (September–October 2005)</b> and <b>Venus PD (January–March 2006)</b>.",
            "A <b>secondary window is Saturn MD / Venus AD (2015–2018, age 37–40)</b>, with Mars Pratyantar in June–August 2016 reactivating the 4th lord. Saturn transiting the 4th house during 2017–2020 supports a second property, land purchase, or major renovation if the 2005 purchase was only a plot or advance.",
            "A tertiary window is <b>Saturn–Mars AD (March 2021 – April 2022, age 43–44)</b> for upgrade, second home, or relocation.",
        ],
        "conclusion": [
            "The native most likely purchased the first house during <b>September 2005 – March 2006</b>, within the Jupiter–Mars Dasa period when Mars as 4th lord was activated. Registration and possession may have completed in 2006–2007 when Jupiter transited the natal 4th house (Scorpio).",
            "The next strong property cluster is <b>2016–2017</b> (Saturn over the 4th, Mars Pratyantar) for a second property, land, or major home investment. The natal chart presents an unambiguous property yoga with no factors of denial.",
        ],
    },
    {
        "num": 6,
        "title": "Marriage Type & Employment Sector",
        "gender": "Female",
        "birth": "4 March 1986, 6:50 AM",
        "place": "Dharmapuri",
        "dob": "1986-03-04",
        "tob": "06:50",
        "question": "(1) Arranged marriage or love marriage? (2) Government employee or private employee?",
        "natal_analysis": [
            "<b>Marriage type:</b> The native has <b>Aquarius lagna (Purva Bhadrapada)</b> with a remarkable stellium of <b>Sun (7th lord), Venus (kalatra karaka), and Jupiter (husband karaka) all in the 1st house</b>. When the 7th lord, Venus, and Jupiter converge in the lagna, the native exercises strong personal choice in partner selection — this is the classical love-marriage signature, not passive arranged alliance.",
            "<b>Mars in the 10th aspects the 5th house</b>, activating romance. <b>Rahu in the 3rd house</b> indicates meeting through courage, communication, siblings, or neighbours — a self-initiated contact path. Moderating factors: <b>Saturn aspects the empty 7th house (Leo)</b>, adding parental consultation and formal family approval; <b>5th lord Mercury in the 2nd house</b> links romance to the family circle. D9 corroboration: Mercury (5th lord) in the 5th house confirms the love element at divisional level.",
            "<b>Employment:</b> <b>Saturn, Moon (6th lord), and Mars (10th lord) together occupy the 10th house (Scorpio)</b>. This triple concentration in the career house, with Saturn as the natural government/service significator and Sun (government karaka) in the lagna, strongly favours public-sector employment over private corporate work.",
        ],
        "aspect_analysis": [
            "<b>Marriage drishti:</b> <b>Sun, Venus, and Jupiter in the lagna each cast 7th aspect on the 7th house (Leo)</b> — triple kalatra significator gaze on the marriage bhava confirms self-chosen partner (love marriage). <b>Saturn from the 10th aspects the 7th house (7th drishti)</b>, adding parental/formal approval after personal choice. <b>Mars from the 10th aspects the 5th house (8th drishti)</b>, activating romance. <b>Rahu from the 3rd aspects the 5th house (3rd drishti)</b>, supporting unconventional/courage-based meeting.",
            "<b>Employment drishti:</b> No planet aspects the 10th house by special drishti, but the three planets <b>occupying</b> the 10th (Saturn, Moon, Mars) provide direct strength. <b>Saturn's 10th-house placement aspects the 4th, 7th, and 12th</b> — linking government service to home stability and institutional work. <b>Jupiter from the lagna aspects the 9th house (9th drishti)</b>, supporting fortune through dharma-aligned public employment.",
        ],
        "dasa_analysis": [
            "Marriage timing windows include <b>Venus MD with Jupiter AD (2007–2010)</b> and <b>Sun MD (2017–2023)</b> as 7th lord period. Career in government service is activated during <b>Moon MD (2023–2033)</b>, particularly <b>Saturn AD (September 2027 – April 2029)</b> when the natural government significator operates as sub-lord while Saturn already occupies the 10th house natally.",
        ],
        "conclusion": [
            "<b>Marriage type: Love-cum-arranged marriage.</b> The primary pattern is love/self-choice (Sun+Venus+Jupiter in lagna), with family formalisation (Saturn aspecting 7th). Pure arranged-only marriage is not supported by the chart.",
            "<b>Employment: Government / public-sector employee.</b> Saturn + Moon (6th lord) + Mars (10th lord) in the 10th house, with Sun in the lagna, indicates government institution, PSU, government hospital, or government-affiliated organisation. Private-sector corporate employment is secondary and would require stronger Mercury–Rahu activation in divisional charts.",
        ],
    },
    {
        "num": 7,
        "title": "Accident",
        "gender": "Male",
        "birth": "2 September 1957, 8:18 AM",
        "place": "Dharmapuri",
        "dob": "1957-09-02",
        "tob": "08:18",
        "question": "Analyse the astrological causes for the accident on 11 July 2005.",
        "event_date": "2005-07-11",
        "event_label": "Accident — 11 July 2005",
        "natal_analysis": [
            "The native has <b>Virgo lagna (Hasta)</b> with a pronounced accident-prone configuration. <b>Ketu (retrograde) in the 8th house (Aries)</b> signifies sudden, unexpected injury — cuts, falls, and blood-related risk. <b>Mars as 8th lord is placed in the 12th house (Leo) with Sun</b>, creating the classic hospitalisation yoga: the lord of sudden danger in the house of loss and confinement.",
            "<b>Sun and Mars together in the 12th house</b> link bodily harm to bed rest and hospitalisation. <b>Venus as 2nd lord (maraka) in the lagna</b> with Jupiter and Mercury makes the body vulnerable during Mars and Rahu periods. <b>Saturn as 6th lord in the 3rd house with Moon</b> suggests accidents through travel, short journeys, or courage-related activities.",
            "Vargottama Sun and Saturn intensify the 8th–12th axis danger theme when activated. The chart does not deny longevity but shows clear vulnerability to injury when malefic Dasa and transits converge.",
        ],
        "aspect_analysis": [
            "<b>Mars (8th lord) from the 12th house aspects the 6th house (8th drishti), 7th house (7th drishti), and 3rd house (4th drishti)</b> — the lord of sudden danger from the hospital house (12th) directly gazes upon the maraka (7th) and disease (6th) houses. This is a primary accident-prone drishti configuration.",
            "<b>Rahu in the 2nd aspects the 8th house (7th drishti), 12th house (11th drishti), and 4th house (3rd drishti)</b> — sudden bodily/financial shock. <b>Ketu in the 8th aspects the 6th house (7th drishti), 12th house (3rd drishti), and 10th house (11th drishti)</b> — nodal axis drishti linking danger to hospitalisation. <b>Saturn from the 3rd aspects the 12th house (10th drishti)</b>, reinforcing confinement after injury. On 11 July 2005, <b>transit Mars and Rahu together in the 7th</b> activate the maraka house by conjunction; <b>transit Ketu on the lagna</b> strikes the body directly.",
        ],
        "dasa_analysis": [
            "On 11 July 2005, the native (age ~47) was running <b>Mars Mahadasha, Rahu Antardasha, and Venus Pratyantar Dasa (approximately June – August 2005)</b>. Mars as MD lord is the primary accident karaka and also the natal 8th lord — providing Dasa permission for a violent or impact-related event.",
            "<b>Rahu Antardasha</b> brings sudden, unexpected occurrences — vehicle accidents, falls, or machinery-related injury. <b>Venus Pratyantar</b> activates the 2nd lord (maraka) seated in the lagna, opening the bodily injury window. The Mars–Rahu–Venus combination at three Dasa levels is a coherent accident signature.",
        ],
        "gochara_analysis": [
            "Transit on 11 July 2005 provides strong corroboration. <b>Mars and Rahu together transit the 7th house (Pisces)</b> — the maraka house activated with sudden danger. <b>Ketu transits the lagna (Virgo)</b>, striking the body directly. <b>Moon in the 12th house (Leo)</b> aligns with natal Sun+Mars in the 12th, confirming hospitalisation.",
            "<b>Jupiter also transiting the lagna</b> provides protection — mitigating fatality and supporting survival and recovery. <b>Saturn, Venus, and Mercury in the 11th</b> indicate expense and recovery through network. Sun in the 10th suggests public visibility or official reporting of the incident.",
        ],
        "conclusion": [
            "The accident on 11 July 2005 is explained by the convergence of natal vulnerability (Ketu in 8th, Mars 8th lord + Sun in 12th), Dasa permission (Mars MD / Rahu AD / Venus PD), and Gochara triggers (Mars+Rahu in 7th, Ketu on lagna, Moon in 12th).",
            "The Parasara method applied sequentially — 6th/8th/12th bhava analysis, then malefic Dasa activation, then transit as final trigger — presents a complete and internally consistent explanation. Jupiter's transit on the lagna accounts for survival and recovery rather than a fatal outcome.",
        ],
    },
    {
        "num": 8,
        "title": "Married or Unmarried?",
        "gender": "Female",
        "birth": "18 May 1985, 6:45 AM",
        "place": "Dharmapuri",
        "dob": "1985-05-18",
        "tob": "06:45",
        "question": "Is she married or unmarried? Analyse natal marriage promise, Dasa evidence, and current status.",
        "natal_analysis": [
            "The native has <b>Taurus lagna (Rohini)</b> with <b>Saturn (retrograde) in the 7th house (Scorpio)</b>. Saturn's occupation of the kalatra bhava makes marriage a central life theme; Saturn here indicates delay or a mature, serious partner rather than denial of marriage — especially at the current age of approximately 41.",
            "<b>Venus as kalatra karaka in Pisces, 11th house</b> supports gain and fulfilment through marriage. <b>Jupiter in Capricorn, 9th house</b> as husband karaka links spouse to fortune and dharma. The <b>9th lord Saturn placed in the 7th with Jupiter in the 9th</b> creates a 7th–9th axis connection indicating a formal, committed alliance with fortune through partnership.",
            "Delay factors: <b>Mars as 7th lord in the lagna with Sun (Manglik)</b> creates matching difficulties and high standards. <b>Moon, Mercury, and Rahu in the 12th house</b> add detachment, possible distance from spouse, or late marriage. <b>Ketu in the 6th house</b> can obstruct until strong Venus/Jupiter periods operate. D9 lagna Taurus with Venus in the 9th confirms spouse bringing fortune.",
        ],
        "aspect_analysis": [
            "<b>Mars (7th lord) in the lagna aspects the 7th house (4th, 7th, and 8th drishti)</b> — the kalatra lord directly aspects its own house where Saturn sits, confirming marriage as a life theme with Manglik intensity. <b>Sun in the lagna also aspects the 7th house (7th drishti)</b>, doubling the gaze on Saturn in Scorpio.",
            "<b>Saturn in the 7th aspects the lagna (3rd drishti), 4th house (10th drishti), and 9th house (3rd drishti)</b> — delay but eventual formal commitment; spouse linked to fortune (9th). <b>Jupiter from the 9th aspects the lagna (5th drishti), 3rd house (9th drishti), and 5th house (5th drishti)</b> — husband karaka supports marriage through dharma. <b>Rahu in the 12th aspects the 6th, 10th, and 2nd houses</b>, explaining obstacles until Venus/Jupiter periods clear the path.",
        ],
        "dasa_analysis": [
            "Multiple marriage windows have passed at marriageable age: <b>Sun MD / Jupiter AD (July 2007 – April 2008, age 22–23)</b>; <b>Sun MD / Saturn AD (April 2008 – April 2009, age 23–24)</b> activating natal Saturn in 7th; <b>Sun MD / Venus AD (June 2010 – June 2011, age 25–26)</b>; and <b>Moon MD / Venus AD (April 2019 – December 2020, age 34–36)</b> as a late-marriage window.",
            "Currently (mid-2026), the native runs <b>Mars Mahadasha (7th lord) with Venus Antardasha (May 2026 – July 2027)</b>. If still unmarried, this is the last strong activation before Rahu Mahadasha — Mars as 7th lord with Venus as kalatra karaka is a powerful marriage trigger.",
        ],
        "conclusion": [
            "Based on natal indicators, Dasa history, and current age, the native is <b>most probably married with delayed marriage</b>. Saturn in the 7th at age 41 typically indicates married status with a late wedding, not lifelong celibacy. The most likely marriage periods are <b>2008–2009</b> (Sun–Saturn AD activating natal Saturn in 7th) or <b>2019–2020</b> (Moon–Venus AD, late-marriage pattern).",
            "If unmarried, the chart explains delay through Manglik dosha (Mars in lagna), the Moon+Rahu+Mercury cluster in the 12th (detachment), and Saturn's delaying influence — with <b>Mars–Venus AD (2026–2027)</b> still open as a remaining window.",
        ],
    },
    {
        "num": 9,
        "title": "Working Abroad",
        "gender": "Male",
        "birth": "7 November 1976, 7:49 PM",
        "place": "Sankarapuram",
        "dob": "1976-11-07",
        "tob": "19:49",
        "question": "He is working abroad — explain the astrological factors responsible.",
        "natal_analysis": [
            "The native has <b>Taurus lagna (Rohini)</b> with one of the clearest foreign-employment yogas in Vedic astrology: <b>the 12th lord Mars placed in the 6th house (Libra)</b>. When the lord of the 12th (foreign lands) occupies the 6th (service/job), earning through overseas employment is structurally indicated — this is the classical videsha-karma yoga.",
            "<b>The 6th house contains a stellium of Sun, Mars, Mercury, and Rahu (retrograde)</b> — daily work in a foreign or unconventional setting. Rahu as the foreign/significator amplifies expatriate themes. <b>Moon and Ketu (retrograde) in the 12th house (Aries)</b> place the mind and residence away from the birthplace, indicating long-term settlement overseas rather than brief travel.",
            "<b>Saturn as 9th lord in the 3rd house</b> links fortune to travel, courage, and relocation. <b>Jupiter (retrograde) in the lagna</b> shows self-expansion through foreign experience. <b>Venus as 10th lord in the 7th house</b> connects career to partnerships, MNCs, and client sites abroad. Budha-Aditya yoga (Sun+Mercury in 6th) supports intellectual/technical service overseas.",
        ],
        "aspect_analysis": [
            "The foreign-work yoga is powerfully reinforced by drishti. <b>Mars (12th lord) from the 6th house aspects the 12th house (8th drishti), 9th house (4th drishti), and lagna (7th drishti)</b> — the classical videsha drishti: foreign lands (12th) linked to daily service (6th) through Mars's special aspects. This is the single strongest drishti confirmation of overseas employment.",
            "<b>Sun and Mercury in the 6th aspect the 12th house (7th drishti)</b> — salaried foreign service. <b>Rahu in the 6th aspects the 12th house (7th drishti)</b>, amplifying expatriate themes. <b>Saturn from the 3rd aspects the 12th house (10th drishti), 9th house (3rd drishti), and 5th house (3rd drishti)</b> — fortune through travel and relocation. <b>Moon and Ketu in the 12th aspect the 6th house (7th drishti)</b>, creating mutual 6th–12th drishti — mind and residence permanently oriented toward foreign service.",
        ],
        "dasa_analysis": [
            "Vimshottari runs from Sun at birth (Krittika nakshatra). <b>Rahu Mahadasha (December 1998 – December 2016, age 22–40)</b> is the primary abroad phase — Rahu is the foreign-lands significator. Key sub-periods: <b>Rahu–Rahu AD (1998–2001)</b> for initial move overseas; <b>Rahu–Mercury AD (2006–2009)</b> for communication/IT/technical job abroad; <b>Rahu–Mars AD (2015–2016)</b> as 12th lord sub-period consolidating foreign service.",
            "<b>Jupiter Mahadasha (December 2016 – December 2032)</b> continues career expansion abroad with Jupiter in the lagna. Currently (mid-2026), <b>Jupiter MD / Venus AD</b> brings stable foreign income — Venus as 10th lord ensures professional comfort overseas.",
        ],
        "conclusion": [
            "The native works abroad because the chart contains a definitive <b>12th lord in 6th house yoga</b>, reinforced by Rahu in the 6th (foreign/unconventional workplace) and Moon+Ketu in the 12th (residence away from homeland). This is structural indication, not accidental circumstance.",
            "<b>Rahu Mahadasha (1998–2016)</b> timed the initial relocation and career build-up overseas; <b>Jupiter Mahadasha</b> sustains and expands it. The 6th-house stellium points to salaried service abroad in IT, engineering, healthcare, technical contract, or MNC posting.",
        ],
    },
    {
        "num": 10,
        "title": "Doctor Profession",
        "gender": "Male",
        "birth": "21 January 1999, 1:07 PM",
        "place": "Chennai",
        "dob": "1999-01-21",
        "tob": "13:07",
        "question": "This person is a doctor — analyse and explain the astrological factors responsible for becoming a doctor.",
        "natal_analysis": [
            "The native has <b>Aries lagna (Krittika)</b> — Mars-ruled, indicating active healing, surgery, and emergency medicine temperament. The medical yoga begins with <b>Mercury as 6th lord (disease/service) placed in the 9th house (Sagittarius)</b> — the classical link between the house of illness and the house of higher education, signifying medical degree through university (MBBS and beyond).",
            "<b>Jupiter as 9th lord and 12th lord is placed in the 12th house (Pisces)</b> — hospital, clinic, and bedside care as the primary life theme. Jupiter is the natural karaka for wisdom, medicine, and the Guru. <b>Sun, Venus, and Ketu in the 10th house (Capricorn)</b> establish an authoritative healing profession: Sun for government medical college/hospital authority, Venus for care, Ketu for specialisation.",
            "<b>Saturn as 10th lord in the lagna</b> makes the medical career the core life identity — disciplined, long-training, and authoritative. <b>Mars as lagna lord in the 7th house</b> adds surgery and patient interaction. <b>Vargottama Mercury</b> strengthens diagnostic intellect. D10 (Dasamsa) confirmation: Venus and Saturn in the 5th (medical skill and specialty), Sun/Mars/Jupiter/Mercury in the 11th (gain from medical career).",
        ],
        "aspect_analysis": [
            "<b>Saturn (10th lord) in the lagna aspects the 10th house (10th drishti), 7th house (7th drishti), and 3rd house (3rd drishti)</b> — the career lord's special 10th aspect directly gazes upon the profession house where Sun, Venus, and Ketu sit, establishing doctor as life identity. <b>Mars from the 7th aspects the 10th house (8th drishti)</b> — surgery karaka's gaze on the career house confirms surgical/medical profession.",
            "<b>Jupiter in the 12th aspects the 6th house (9th drishti), 8th house (5th drishti), and 4th house (5th drishti)</b> — Guru's drishti links hospital (12th) to disease/service (6th) and longevity/surgery (8th). <b>Rahu in the 4th aspects the 6th house (3rd drishti), 10th house (7th drishti), and 2nd house (11th drishti)</b> — unconventional medical path or specialisation. <b>Ketu in the 10th aspects the 12th house (7th drishti)</b>, connecting career to hospital confinement and bedside care.",
        ],
        "dasa_analysis": [
            "Vimshottari runs from Jupiter at birth (Purva Bhadrapada). <b>Jupiter MD (1999 – 2012)</b> oriented the native toward healing/hospital environments early in life. <b>Saturn MD (2012 – 2031)</b> as 10th lord governs medical degree completion and career establishment.",
            "The critical education window is <b>Saturn MD / Mercury AD (September 2015 – May 2018, age 16–19)</b> — Mercury as 6th lord in the 9th house activated as sub-lord during the peak medical college and internship phase. Currently in <b>Saturn MD / Rahu AD</b>, the native may be pursuing specialisation, foreign posting, or an unconventional medical branch.",
        ],
        "conclusion": [
            "The native became a doctor through the integrated operation of: (1) <b>6th lord in 9th</b> — medical higher education; (2) <b>Jupiter in 12th</b> — hospital and healing institution as life theme; (3) <b>Sun+Venus+Ketu in 10th</b> — authoritative healing career with specialisation; (4) <b>Saturn (10th lord) in lagna</b> — disciplined doctor identity; (5) D10 confirmation with Venus in the 5th and medical planets in the 11th; (6) <b>Saturn–Mercury Dasa (2015–2018)</b> timing the medical graduation phase.",
            "The Parasara method applied through karakas (Sun, Mercury, Jupiter), bhavas (6th, 9th, 10th, 12th), divisional charts (D9, D10), and Dasa activation presents a complete and internally consistent medical profession analysis.",
        ],
    },
]
